### ISSUE TITLE
redmine_better_overview not installed

### ISSUE THREAD

**Issue by sytkosa** [maxrossello/redmine_better_overview#1]
Environment:
  Redmine version             3.4.6.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                    4.2.8
  Environment                    production
  Database adapter            Mysql2

Error log:

```
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/var/www/redmine/lib/redmine/plugin.rb:123:in `find'
/var/www/redmine/lib/redmine/plugin.rb:251:in `requires_redmine_plugin'
/var/www/redmine/plugins/redmine_better_overview/init.rb:16:in `block in <top (required)>'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rbenv/versions/2.3.5/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.3.5/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by maxrossello** [comment]
redmine_base_deface is a needed dependency. Did you install it as well?

**Comment by sytkosa** [comment]
base_deface plugin is not installed.
```
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: deface (>= 0) and deface (>= 1.1.0). Bundler cannot continue.

 #  from /var/www/redmine/plugins/redmine_base_deface/Gemfile:1
 #  -------------------------------------------
 >  gem 'deface', '>= 1.1.0'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /var/www/redmine/Gemfile:113
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

```
What to do now ?

**Comment by maxrossello** [comment]
there's another plugin specifying a different requirement for deface. Either remove that plugin or align its Gemfile to require the maximum among the minimum versions of deface required by every plugin.

Unfortunately this issue is common with plugin gem dependencies

**Comment by maxrossello** [comment]
in other words, change the Gemfile of that plugin from

    gem 'deface'

to

    gem 'deface', '>= 1.1.0'

**Comment by sytkosa** [comment]
Already done.

Not compatible

additionals plugin cannot be used with redmine_base_deface plugin

```
rake aborted!

additionals plugin cannot be used with redmine_base_deface plugin'.
/var/www/redmine/plugins/additionals/lib/additionals.rb:75:in `block in incompatible_plugins'
/var/www/redmine/plugins/additionals/lib/additionals.rb:74:in `each'
/var/www/redmine/plugins/additionals/lib/additionals.rb:74:in `incompatible_plugins'
/var/www/redmine/plugins/additionals/lib/additionals.rb:7:in `setup'
/var/www/redmine/plugins/additionals/init.rb:43:in `block in <top (required)>'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rbenv/versions/2.3.5/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.3.5/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by sytkosa** [comment]
It all worked.

Updated plugin additional

**Comment by maxrossello** [comment]
ok. Make anyways sure you use last version of additionals. I see they also declare deface version >=1.1.0 and redmine_base_deface is not in the list of incompatible plugins

      incompatible_plugins(%w[redmine_tweaks
                              redmine_issue_control_panel
                              redmine_editauthor
                              redmine_changeauthor
                              redmine_auto_watch])
